### ISSUE TITLE
notes: couchDB configuration

### ISSUE THREAD

**Issue by r1de** [DanRuderman/EmComMap#7]
This is just some notes of what I found while installing this on a debian/raspbian Buster system:

I gave up changing the local.ini file and was just using the web configuration on port 5984, but I am not sure *where* the web configuration is saving it's values **to**.

I had to enable CORS in the http section of the web config, then there is a CORS section of it's own.

I went into there and enabled the origins "*" option.

I then had to click "add option" button in the interface and created the other CORS options for headers and methods.

Then adding the users to the database permissions with the syntax of "["kg6wxc", "w6bi"] just does not work, but adding the users singularly, just typing 1 username each time (ie: kg6wxc), without the quotes, worked just fine.

**Comment by DanRuderman** [comment]
Thanks - will experiment and update docs.

**Comment by DanRuderman** [comment]
Updated instructions with these notes.
